# Generated by Django 5.2.5 on 2025-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='protein_goal',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='user',
            name='todays_protein',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
