# Generated by Django 5.2.5 on 2025-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_protein_goal_user_todays_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='todays_protein',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
