# Generated by Django 5.2.5 on 2025-09-24 20:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_todays_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='protein_last_update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
