# Generated by Django 5.2.5 on 2025-09-30 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_exercise_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='protein_goal',
            field=models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
