# Generated by Django 5.2.5 on 2025-10-06 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_protein_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='protein_goal',
            field=models.PositiveIntegerField(default=150, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='todays_protein',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
    ]
